# Generated by Django 4.1 on 2022-08-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id_object_type', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text='Object type name.', max_length=20)),
                ('description_object_type', models.CharField(help_text='Object type description.', max_length=50)),
            ],
            options={
                'ordering': ['object_type'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('parameter', models.CharField(help_text='Parameter name.', max_length=20)),
                ('measure_unit', models.CharField(help_text='Object type description.', max_length=10)),
                ('id_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.objecttypes')),
            ],
            options={
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='ParameterTypes',
            fields=[
                ('id_parameter_type', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_type', models.CharField(help_text='Type name.', max_length=10)),
                ('description_parameter_type', models.CharField(help_text='Type name description.', max_length=50)),
            ],
            options={
                'ordering': ['parameter_type'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='User name. Use letters of the English alphabet and numbers.', max_length=10)),
                ('phone_number', models.CharField(help_text="The user's phone number. Use numbers and the '+' symbol.", max_length=12)),
                ('password', models.CharField(help_text='Password hash.', max_length=20)),
                ('description', models.CharField(help_text='User description.', max_length=50)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PermissionParameters',
            fields=[
                ('id_permission_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField()),
                ('create', models.BooleanField()),
                ('id_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.parameters')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.users')),
            ],
            options={
                'ordering': ['id_permission_parameter'],
            },
        ),
        migrations.CreateModel(
            name='PermissionObject',
            fields=[
                ('id_permission_object', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField()),
                ('create', models.BooleanField()),
                ('id_oblect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.objects')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.users')),
            ],
            options={
                'ordering': ['id_permission_object'],
            },
        ),
        migrations.AddField(
            model_name='parameters',
            name='id_parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.parametertypes'),
        ),
        migrations.AddField(
            model_name='objects',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.parametertypes'),
        ),
        migrations.AddField(
            model_name='objects',
            name='id_object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.objecttypes'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id_record', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(help_text='Record date time.')),
                ('value', models.CharField(help_text='Value record', max_length=10)),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.objects')),
                ('id_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.parameters')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.users')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
