# Generated by Django 4.1 on 2022-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='id',
        ),
        migrations.AlterField(
            model_name='objects',
            name='id_object',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
