# Generated by Django 4.1 on 2022-08-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_data_id_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionobject',
            old_name='id_oblect',
            new_name='id_object',
        ),
        migrations.AddField(
            model_name='data',
            name='id_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.objects'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='id_object',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
