# Generated by Django 4.1 on 2022-08-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_id_oblect_permissionobject_id_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.objects'),
        ),
    ]
