# Generated by Django 4.1 on 2022-08-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_data_id_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id_object',
        ),
    ]
