# Generated by Django 4.1 on 2022-08-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_data_id_object'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
