# Generated by Django 4.1 on 2022-08-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_objects_id_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionobject',
            name='id_object',
        ),
        migrations.RemoveField(
            model_name='permissionobject',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Objects',
        ),
        migrations.DeleteModel(
            name='PermissionObject',
        ),
    ]
