# Generated by Django 4.1 on 2022-08-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_data_id_user_delete_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameters',
            options={'ordering': ['id_parameter']},
        ),
    ]
