# Generated by Django 4.1 on 2022-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_parameters_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(help_text='Value record', max_length=50),
        ),
    ]
