# Generated by Django 4.1 on 2022-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_data_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='object_description',
            field=models.CharField(default='-', help_text='Description', max_length=50),
        ),
    ]
