# Generated by Django 4.0.6 on 2022-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_parameters_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='default_value',
            field=models.CharField(default='', help_text='Default value', max_length=100),
        ),
    ]
