# Generated by Django 4.0.6 on 2022-09-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_parameters_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='default_value',
            field=models.CharField(blank=True, default='', help_text='Default value', max_length=100),
        ),
    ]
