# Generated by Django 4.0.6 on 2022-09-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_parameters_default_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['datetime_record']},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='datetime',
            new_name='datetime_record',
        ),
    ]
