# Generated by Django 4.0.6 on 2022-09-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_data_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime_record',
            field=models.DateTimeField(auto_now_add=True, help_text='Record date time.'),
        ),
    ]
