# Generated by Django 4.0.6 on 2022-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_data_datetime_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='datetime_data',
            field=models.DateTimeField(default='2022-01-01 00:00:00', help_text='Date and time of data.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='datetime_record',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time of record.'),
        ),
    ]
