# Generated by Django 4.0.6 on 2022-09-12 09:54

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_data_datetime_data_alter_data_datetime_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime_data',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now, help_text='Date and time of data.'),
        ),
    ]
