# Generated by Django 4.0.6 on 2022-09-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_data_datetime_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='id_object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.objecttypes'),
        ),
    ]
