# Generated by Django 4.0.6 on 2022-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_objects_id_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(help_text='Value record', max_length=200),
        ),
        migrations.AlterField(
            model_name='objects',
            name='object_description',
            field=models.CharField(default='-', help_text='Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='default_value',
            field=models.CharField(blank=True, default='', help_text='Default value', max_length=200),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='parameter',
            field=models.CharField(help_text='Parameter name.', max_length=200),
        ),
    ]
