# Generated by Django 4.0.6 on 2022-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_data_value_alter_objects_object_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='object_description',
            field=models.CharField(default='-', help_text='Description', max_length=200, unique=True),
        ),
    ]
